
/*
  login
*/

export const CHANGE_FIELD_USER_INPUT = 'CHANGE_FIELD_USER_INPUT';
export const CHANGE_FIELD_PASS_INPUT = 'CHANGE_FIELD_PASS_INPUT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

/*
  tree management
*/

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';

export const CHANGE_FIELD_NEW_ITEM_NAME_INPUT = 'CHANGE_FIELD_NEW_ITEM_NAME_INPUT';
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
